name: hayah_karema
description: Hayah Karema Mobile App
version: 1.0.6+6
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  rxdart: ^0.27.3
  get: ^4.6.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  form_field_validator: ^1.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.20
  google_fonts: ^3.0.1
  barbecue: ^0.4.0
  ansicolor: ^2.0.1
  progress_indicators: ^1.0.0
  dotted_border: ^2.0.0+2
  pin_code_fields: ^7.3.0
  sleek_circular_slider: ^2.0.1
  image_picker: ^0.8.4+11
  carousel_slider: ^4.0.0
  buttons_tabbar: ^1.3.4
  readmore: ^2.1.0
  video_player: ^2.3.0
  chewie: ^1.3.1
  youtube_player_flutter: ^8.0.0
  share_plus: ^4.0.3
  rive: ^0.9.0
  flutter_html: ^3.0.0-alpha.3
  flutter_screenutil: ^5.5.3+2
  flutter_rating_bar: ^4.0.1
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^4.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/icons_font/MyCustomIcons.ttf
