/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData add_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_green = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData advert = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_black = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_green = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData awards = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_orange = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balance_orange = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_heart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chapter = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_orange = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_green = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cubones = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date_of_death = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData current_orange = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_red = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_green = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_orange = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_green = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fawry = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_sales = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giftcard = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduated = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handheart = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData honor_category = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData honorbord = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_basket = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ins_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ins_1_1 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_orange = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_white = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manage_account = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marketplacec = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partners = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData points = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post_options = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_empty = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_filled = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate_light = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate_orange = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_11213 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_11213_1 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_circle = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad_emojie = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_green = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sell_now = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shares_green = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_oranges = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidemenu = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stars_green = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threedots_gray = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_lingth = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trainingprograms = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData views_green = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData village = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yalla = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accebility_audio_btn = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accebility_sign_btn = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData active = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activities = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
